### ISSUE TITLE
Add Connection.isClosed() (or Entity.isClosed()) so that we can know before doing any call if a ConnectionClosedException will throw

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-apis#215] opened 2017-04-20 16:50 UTC
In M&M, we have several use cases where the connection can be broken when servers are all down, and any call to entities will throw a ConnectionClosedException.

So we have some code like that:

```
  private boolean isConnectionClosed(NmsEnity entity){
    try {
      entity.readTopology();
      return false;
    } catch (ConnectionClosedException e) {
      return true;
    } 
  }
```

This is a hack that we have to do because voltron client does not make us aware when it closes the connection. We even do not have a flag to check.

So we'd like to have at least a `Connection.isClosed()` method to avoid doing such hack and trying to call an entity each time.

Side note: voltron client knows it since it creates a warning when doing the call:

```
2017-04-20 09:52:22,495 [Time-limited test] WARN com.tc.net.protocol.tcm.TCMessageImpl - message not sent
java.io.IOException: connection not established
	at com.tc.net.protocol.transport.MessageTransportBase.send(MessageTransportBase.java:185)
	at com.tc.net.protocol.tcm.AbstractMessageChannel.send(AbstractMessageChannel.java:218)
	at com.tc.net.protocol.tcm.ClientMessageChannelImpl.send(ClientMessageChannelImpl.java:135)
	at com.tc.net.protocol.tcm.TCMessageImpl.basicSend(TCMessageImpl.java:399)
	at com.tc.net.protocol.tcm.TCMessageImpl.send(TCMessageImpl.java:385)
	at com.tc.object.InFlightMessage.send(InFlightMessage.java:88)
	at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:138)
	at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:124)
	at com.tc.object.ClientEntityManagerImpl$2.addSingleThreaded(ClientEntityManagerImpl.java:165)
	at com.tc.object.ClientEntityManagerImpl.createInFlightMessageAfterAcks(ClientEntityManagerImpl.java:554)
	at com.tc.object.ClientEntityManagerImpl.invokeAction(ClientEntityManagerImpl.java:291)
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl.invoke(EntityClientEndpointImpl.java:174)
	at ...
```

CC @anthonydahanne @ljacomet @henri-tremblay @anthonydahanne @myronkscott @ChrisGreenaway

**Comment by ChrisGreenaway** [comment] 2017-04-20 16:57
Is this a duplicate of https://github.com/Terracotta-OSS/terracotta-apis/issues/210 ?

**Comment by mathieucarbou** [comment] 2017-04-20 17:01
@ChrisGreenaway : I have renamed #210 to better understand the difference ;-).

- #215 is so that we can know that a connection (more specifically endpoint) has been closed and is not usable anymore. Because it is the case when we kill an active and then restart it. We cannot use the entities anymore and it fails with a ConnectionClosedException. So we should be able to get this state before doing any entity call.

- #210 is to add a flag on the connection when Connection.close() is called, so that any other libraries or services using the same connection object can know that a close has been  requested on the connection, and, consequently, that any call they will make won't make it, and also so that the ycan shutdown or clean resources properly.

**Comment by ChrisGreenaway** [comment] 2017-04-21 08:04
Do you want this state in order to report the state in the M&M GUI, or do you want the state in order to make a decision about what operations to perform with the Voltron API? For example, you say: "we should be able to get this state before doing any entity call" - does that mean you want to make the entity call if and only if ConnectionClosedException would not have been generated?

**Comment by mathieucarbou** [comment] 2017-04-21 13:24
Yes, I _want to make the entity call if and only if ConnectionClosedException would not have been 
generated

Because when the servers are not restartable, the connection is closed, not by us when the serevr restarts, and we have no way to know that. Here is how to reproduce:

```
    Properties properties = new Properties()
    properties.setProperty(ConnectionPropertyNames.CONNECTION_TIMEOUT, "10000")
    Connection connection = ConnectionFactory.connect(connectionURI, properties)
    NmsEntityFactory entityFactory = new NmsEntityFactory(connection, "NmsEntity")
    NmsEntity nmsEntity = entityFactory.retrieveOrCreate(new NmsConfig().setStripeName("my-stripe"))

    println nmsEntity.readTopology().get().toMap().toPrettyJson()

    CLUSTER.resource.clusterControl.terminateAllServers()

    try {
      nmsEntity.readTopology().get(2, TimeUnit.SECONDS).toMap().toPrettyJson()
      fail()
    } catch (Exception e) {
      e.printStackTrace() // Timeout exception, which is normal, because no server is there so our voltron invokation times out
    }

    CLUSTER.resource.clusterControl.startAllServers()
    CLUSTER.resource.clusterControl.waitForActive()

    println nmsEntity.readTopology().get().toMap().toPrettyJson() // throws ConnectionClosedException
```

we have no way to know that the connection has been closed! So we have to do a hack by calling a voltron method like this:

```
private boolean isConnectionClosed(NmsEnity entity){
    try {
      entity.readTopology();
      return false;
    } catch (ConnectionClosedException e) {
      return true;
    } 
  }
```

This is quite an obvious use case isn't it ? Being able to know that the connection is closed and not usable anymore.

Note: when the servers are restartable, this is different. the last invokation will work since the states on the servers are back. So Connection.isClosed() should return false in case of a restartable server.

**Comment by ljacomet** [comment] 2017-04-21 13:39
I have some doubts around the whole discussion. Mostly because basing any decision on a connection being closed or not is fundamentally a race condition in any multi threaded environment. But maybe there is more that I do not see / understand.

**Comment by cschanck** [comment] 2017-04-21 14:09
I have some trouble with this: **"I want to make the entity call if and only if ConnectionClosedException would not have been generated And also: I want a way to know in advance from some places if the connection is still usable or must be recycled..."** because as Louis points out, you can't ever know that. The only useful way to find that out is to call the method and catch the exception. But I am puzzled at the hack you are doing; why have an isClosed() method at all -- the connection state is like Schroedinger's Cat. Why do you want an isClosed() as opposed to just trying to perform an operation and handling the exception?

**Comment by henri-tremblay** [comment] 2017-04-21 14:21
There is ;-) The flag already exists internally in fact. So indeed there is a race condition. So if you want to be sure a connection is dead, you need to try it more or less.

This `isClosed()` in fact tells if someone asked to close the connection. We used it to prevent the client from doing stuff after the close was requested (by the client). So any async messages are discarded for example. During integration tests it is the kinda thing that you check in `@After` before doing your cleanup.

But then, I am a bit lost between #210 and this one. So I might be talking about the other. In our current case, it depends if we want a definitive answer or not. If we know it's dead, it can however be a shortcut.

```
    try {
        if(conn.isClosed()) {
            return false;
        }
        entity.readTopology();
        return false;
    } catch (ConnectionClosedException e) {
      return true;
    } 
  }
```

**Comment by myronkscott** [comment] 2017-04-21 15:03
The use-case initially listed by @mathieucarbou is an exceptional case and I believe it should be handled with exceptions.  When the cluster disappears like that, all the remote state is gone and is never coming back.  The connection is not just closed, it is invalid and any associated entity or application state is invalid.  I don't know if there is much todo other than restart the client application so why have a method that exposes this state?

**Comment by mathieucarbou** [comment] 2017-04-21 17:08
right @myronkscott ! so in this case, what we'd like is to know that a tc connection is not usable anymore and should be removed and crecreated. M&N keeps a map of connections per stripe.

When the servers are restartable, the connection __must not be closed__ otherwise we will be impacted by this 2min reconnect delay. But if the server is not restartable, then we have to know from one way or the other that the connection is __invalid__ and then we can re-create a new one.

If I want to do something that works in both cases, I have to do that:

```
    Properties properties = new Properties()
    properties.setProperty(ConnectionPropertyNames.CONNECTION_TIMEOUT, "10000")
    Connection connection = ConnectionFactory.connect(connectionURI, properties)
    NmsEntityFactory entityFactory = new NmsEntityFactory(connection, "NmsEntity")
    NmsEntity nmsEntity = entityFactory.retrieveOrCreate(new NmsConfig().setStripeName("my-stripe"))

    println nmsEntity.readTopology().get().toMap().toPrettyJson()

    CLUSTER.resource.clusterControl.terminateAllServers()

    try {
      nmsEntity.readTopology().get(2, TimeUnit.SECONDS).toMap().toPrettyJson()
      fail()
    } catch (Exception e) {
      e.printStackTrace() // Timeout
    }

    CLUSTER.resource.clusterControl.startAllServers()
    CLUSTER.resource.clusterControl.waitForActive()

    try {
      // this line will work for a restartable server
      println nmsEntity.readTopology().get().toMap().toPrettyJson()

    } catch (ConnectionClosedException e) {
      // we will go there if the server is not restartable
      connection = ConnectionFactory.connect(connectionURI, properties)
      entityFactory = new NmsEntityFactory(connection, "NmsEntity")
      nmsEntity = entityFactory.retrieveOrCreate(new NmsConfig().setStripeName("my-stripe"))
      println nmsEntity.readTopology().get().toMap().toPrettyJson()
    }
```

What I would like is to not have a different behavior to handle on the connection, __so that I can avoid this 2min reconnect delay__

If each time we have a timeout or something wrong occuring we could just close the connection and then reconnect after when the server is up again, and we are not impacted by the reconnect delay, then it would be the best.

But we must find a way to avoid this reconnect delay, and for the moment, the TC Connection has a different behavior whether the server is restartable or not.

**Comment by myronkscott** [comment] 2017-04-22 00:55
It's hard without context but shouldn't you be tracking your entity and not the connection?  The entity will be notified if it is unexpectedly disconnected.

**Comment by myronkscott** [comment] 2017-04-26 05:32
Will not implement.  Requester is using ```didDisconnectionUnexpectedly()``` instead

**Closed by myronkscott** 2017-04-26 05:32 UTC
Labels: enhancement
